name: QA

on:
  schedule:
    - cron: 0 1 * * *

jobs:
  qa:
    name: Quality Assurance
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install Deps
        run: yarn
      - name: Compile Script
        run: yarn qa:compile
      - name: Start QA
        run: |
          git config --global core.quotePath false
          git config --global core.precomposeunicode true
          yarn qa
      - name: Commit any changes
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            exit 0;
          else
            hub config --global hub.protocol https;
            hub config --global user.email "${GITHUB_EMAIL}";
            hub config --global user.name "${GITHUB_USER}";
            hub remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git";
            git config --local user.email "${GITHUB_EMAIL}";
            git config --local user.name "${GITHUB_USER}";
            git checkout -b semid/qa/`date +%F-%H-%M`;
            git commit -sam "♻️ Refactoring";
            hub pull-request -p -l "automation" -m "🤖 Daily QA" -m "*bleep bloop* I've prettified and refactored some Presences, feel free to fix or remove the ones that break.";
          fi
        env:
          GITHUB_USER: SeMiD
          GITHUB_EMAIL: contact@premid.app
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE }}